### ISSUE TITLE
Handlers Manually Option  

### ISSUE THREAD

**Issue by fdhsdrdark** [alsami/MediatR.Extensions.Autofac.DependencyInjection#10]
Not a issue, just a question please: 
Is there a way to register Handlers manually?

That is, on start up - based on configuration register the required Handlers.
This will allow to have multiple handlers implementation for the same command and decide witch implementation will be used.

Thank you very much for any response.

**Comment by alsami** [comment]
Currently that is not possible. I've started [building something](https://github.com/alsami/MediatR.Extensions.Autofac.DependencyInjection/blob/main/src/MediatR.Extensions.Autofac.DependencyInjection/MediatRConfiguration.cs) that would allow configuration but haven't had the chance to finish it.

I will try to get this done in the next days. 

Just out of curiousity: why two different command-handlers for same command? Does it relate to multi-tenancy?

**Comment by alsami** [comment]
Version `8.2.0` will be released shortly.

You can basically now do the following:

```csharp
var configuration = MediatRConfigurationBuilder
    .Create(typeof(ResponseCommand).Assembly)
    // this will register all mediatr open-generic types
    // except of types derived from IRequestHandler<TRequest, TResponse>
    .WithRequestHandlersManuallyRegistered()
    .Build();
    
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterMediatR(configuration);
containerBuilder.RegisterType<MyHandlerType>().As<IRequestHandler<MyCommand, MyResponse>>();
var container = containerBuilder.Build();
// and so on
```
