### ISSUE TITLE
Add option for registering as SingleInstance

### ISSUE THREAD

**Issue by jackerman88** [alsami/MediatR.Extensions.Autofac.DependencyInjection#13]
I've recently run into a situation where I need an INotificationHandler registered as a singleton, but there's not currently any built-in support for it. I've managed to make it work by manually registering the specific class after registering MediatR since last-in wins for registrations, but it'd be nice for it to be supported as part of this project.

One potential implementation idea I had is to add an optional attribute to whatever class implements the MediatR interfaces that allows you to specify if a class should be singleton (and potentially other registration options that Autofac supports).

**Comment by alsami** [comment]
Hey there. Just curious, why would you want to register something like that as a singleton?

I was thinking about providing any option but I would definitely only provide `transient` or `scoped` support. IMO registering a command-handler or any other `MediatR` dependencies as a singleton sounds like an anti-pattern.

Also, the support for defining the life-time of a dependency would be global and not per type. Meaning if you were to pass `transient` as the scope, everything would be registered as transient.

**Comment by jackerman88** [comment]
So here's my current (very simplified) use-case:

```
public class WebClient : INotificationHandler<LoggedInEvent>, INotificationHandler<MakeRequestEvent>
{
	private IRequestClient requestClient;
	
	public async Task Handle(LoggedInEvent notification, CancellationToken token)
	{
		requestClient = new RequestClient(notification.someInfo);
	}
	
	public async Task Handle(MakeRequestEvent notification, CancellationToken token)
	{
		await requestClient.MakeRequest(notifciation.someOtherInfo);
	}
}
```

The request client needs to be created with information that is available after the user logs in (which fires the LoggedInEvent), and when the MakeRequestEvent is fired we need to execute MakeRequest on the client that was originally created with the info from the LoggedInEvent.

I need WebClient to be registered as a singleton to ensure that when the MakeRequestEvent is fired it uses the same requestClient (and therefore the same WebClient instance) that was created after the LoggedInEvent fired.

**Comment by alsami** [comment]
I think you should make sure to register that specific dependency as a singleton instead and if that is not possible find another way to resolve it as required.

I am sorry but I won't be adding a possibility to register any services required for the lib to be registered as a singleton.

If you provide more context of the problem at hand I can try to help you to find a different solution though.

**Comment by alsami** [comment]
Options been added to define scopes as transient or scoped. Closing this now, since no additional context has been provided.
