### ISSUE TITLE
NRE with customBehaviorTypes in MediatRModule

### ISSUE THREAD

**Issue by krasninja** [alsami/MediatR.Extensions.Autofac.DependencyInjection#4]
I used to use this registration code:
```
builder.AddMediatR(
    typeof(UseCases.Users.AuthenticateUser.LoginUserCommand).GetTypeInfo().Assembly,
    typeof(UseCases.Integrations.ImportFromCrm.ImportFromCrmCommand).GetTypeInfo().Assembly
);
```

However, starting 3.1.0 this doesn't work. I'm getting the NRE exception on https://github.com/cleancodelabs/MediatR.Extensions.Autofac.DependencyInjection/blob/master/src/MediatR.Extensions.Autofac.DependencyInjection/MediatRModule.cs#L44

Had to change to:

```
builder.AddMediatR(
    new Type[] { },
    new[]
    {
        typeof(UseCases.Users.AuthenticateUser.LoginUserCommand).GetTypeInfo().Assembly,
        typeof(UseCases.Integrations.ImportFromCrm.ImportFromCrmCommand).GetTypeInfo().Assembly
    });
```

It seems to me that `customBehaviorTypes` is initialized with null by default incorrectly.

**Comment by alsami** [comment]
Thanks for reporting this. Version 3.1.1 including the fix is currently being [built](https://travis-ci.com/cleancodelabs/MediatR.Extensions.Autofac.DependencyInjection/builds/142354876).

**Comment by krasninja** [comment]
Thanks for the fast fix!
