### ISSUE TITLE
Support for IRequestPostProcessor and IRequestPreProcessor

### ISSUE THREAD

**Issue by dconsavi** [alsami/MediatR.Extensions.Autofac.DependencyInjection#7]
Hello,

I noticed that the [IRequestPostProcessor](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Pipeline/IRequestPostProcessor.cs) and [IRequestPreProcessor](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Pipeline/IRequestPreProcessor.cs) interfaces are not automatically register with this great [package](https://github.com/alsami/MediatR.Extensions.Autofac.DependencyInjection/blob/68b8ee86830eee64d2a9da564ef4d0f001771d3b/src/MediatR.Extensions.Autofac.DependencyInjection/MediatRModule.cs#L26).
Is it a will or is it something that's missing?

Regards,
Dylan

**Comment by alsami** [comment]
Hey, thanks for reporting this. I will add support for it since it should be working the same way as the other types.

**Comment by alsami** [comment]
[7.3.0](https://www.nuget.org/packages/MediatR.Extensions.Autofac.DependencyInjection/7.3.0) just has been pushed to nuget.org and should be online in a few minutes.
